services:
  app:
    build: .
    container_name: dashboard_app
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        # This new condition tells 'app' to wait for the
        # 'db' healthcheck to pass before starting.
        condition: service_healthy 
  
  db:
    image: postgres:13
    container_name: dashboard_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=dashboarddb
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dashboarddb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: